import Foundation
import AppKit
import Vision
import UniformTypeIdentifiers

/// Owns the shelf contents and their on-disk backing files.
@MainActor
final class ShelfStore: ObservableObject {
    @Published private(set) var items: [ShelfItem] = []

    /// When on, anything you copy (⌘C) is auto-added to the shelf.
    @Published var isWatching: Bool {
        didSet { UserDefaults.standard.set(isWatching, forKey: Self.watchKey) }
    }

    private static let watchKey = "autoClipboardWatch"

    private let baseURL: URL
    private let filesURL: URL
    private let manifestURL: URL

    private var clipboardTimer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    init() {
        let support = FileManager.default.urls(for: .applicationSupportDirectory,
                                               in: .userDomainMask).first!
        baseURL = support.appendingPathComponent("CopyCat", isDirectory: true)
        filesURL = baseURL.appendingPathComponent("files", isDirectory: true)
        manifestURL = baseURL.appendingPathComponent("manifest.json")

        isWatching = UserDefaults.standard.object(forKey: Self.watchKey) as? Bool ?? true

        try? FileManager.default.createDirectory(at: filesURL,
                                                 withIntermediateDirectories: true)
        load()
        startClipboardWatch()
    }

    // MARK: - Auto clipboard watcher

    private func startClipboardWatch() {
        clipboardTimer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.pollClipboard() }
        }
    }

    /// Pasteboard types that mark sensitive/transient content we must never store.
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private func pollClipboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard isWatching else { return }

        // Privacy: skip password managers and other concealed/transient writes.
        let types = (pb.types ?? []).map(\.rawValue)
        if types.contains(where: Self.concealedTypes.contains) { return }
        // Don't auto-grab file copies (could be huge); those come via drag/drop.
        if pb.types?.contains(.fileURL) == true { return }

        if let images = pb.readObjects(forClasses: [NSImage.self]) as? [NSImage],
           let image = images.first {
            addImage(image)
        } else if let string = pb.string(forType: .string) {
            // Dedupe against the most recent text item.
            if let top = items.first, top.kind == .text || top.kind == .link,
               top.text == string.trimmingCharacters(in: .whitespacesAndNewlines) {
                return
            }
            addText(string)
        }
    }

    // MARK: - Disk location

    /// Absolute URL of the file backing an item, if any.
    func fileURL(for item: ShelfItem) -> URL? {
        guard let name = item.fileName else { return nil }
        return filesURL.appendingPathComponent(name)
    }

    func image(for item: ShelfItem) -> NSImage? {
        guard item.kind == .image, let url = fileURL(for: item) else { return nil }
        return NSImage(contentsOf: url)
    }

    // MARK: - Adding

    @discardableResult
    func addText(_ string: String) -> ShelfItem? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        let isLink = looksLikeURL(trimmed)
        let item = ShelfItem(kind: isLink ? .link : .text,
                             name: isLink ? prettyHost(trimmed) : firstLine(trimmed),
                             text: trimmed)
        insert(item)
        return item
    }

    @discardableResult
    func addImage(_ image: NSImage, suggestedName: String = "Image") -> ShelfItem? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else { return nil }

        let id = UUID()
        let fileName = "\(id.uuidString).png"
        let dest = filesURL.appendingPathComponent(fileName)
        do {
            try png.write(to: dest)
        } catch {
            return nil
        }
        let item = ShelfItem(id: id, kind: .image, name: suggestedName, fileName: fileName)
        insert(item)
        return item
    }

    /// Copies an external file into the store so it can be re-dragged later.
    @discardableResult
    func addFile(at url: URL) -> ShelfItem? {
        let id = UUID()
        let ext = url.pathExtension
        let storedName = ext.isEmpty ? id.uuidString : "\(id.uuidString).\(ext)"
        let dest = filesURL.appendingPathComponent(storedName)
        do {
            if FileManager.default.fileExists(atPath: dest.path) {
                try FileManager.default.removeItem(at: dest)
            }
            try FileManager.default.copyItem(at: url, to: dest)
        } catch {
            return nil
        }

        let isImage = (try? url.resourceValues(forKeys: [.contentTypeKey]))?
            .contentType?.conforms(to: .image) ?? false
        let item = ShelfItem(id: id,
                             kind: isImage ? .image : .file,
                             name: url.lastPathComponent,
                             fileName: storedName)
        insert(item)
        return item
    }

    /// Pulls whatever is currently on the system clipboard onto the shelf.
    @discardableResult
    func captureClipboard() -> ShelfItem? {
        capture(from: .general)
    }

    /// Adds the contents of any pasteboard (clipboard or a drag) to the shelf.
    /// Used both by the "grab clipboard" button and drops onto the menu bar icon.
    @discardableResult
    func capture(from pb: NSPasteboard) -> ShelfItem? {
        if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL], !urls.isEmpty {
            var last: ShelfItem?
            for url in urls {
                last = url.isFileURL ? addFile(at: url) : addText(url.absoluteString)
            }
            return last
        }
        if let images = pb.readObjects(forClasses: [NSImage.self]) as? [NSImage],
           let image = images.first {
            return addImage(image)
        }
        if let string = pb.string(forType: .string) {
            return addText(string)
        }
        return nil
    }

    // MARK: - Mutating

    func remove(_ item: ShelfItem) {
        if let url = fileURL(for: item) {
            try? FileManager.default.removeItem(at: url)
        }
        items.removeAll { $0.id == item.id }
        save()
    }

    func clearAll() {
        for item in items {
            if let url = fileURL(for: item) {
                try? FileManager.default.removeItem(at: url)
            }
        }
        items.removeAll()
        save()
    }

    /// True when there's at least one text/link item to "copy all".
    var hasTextItems: Bool {
        items.contains { $0.kind == .text || $0.kind == .link }
    }

    /// Concatenates every text/link item, in copy order (#1 first), onto the
    /// clipboard as one newline-separated block.
    func copyAllInOrder() {
        let ordered = items.reversed().compactMap { item -> String? in
            switch item.kind {
            case .text, .link: return item.text
            default: return nil
            }
        }
        guard !ordered.isEmpty else { return }
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(ordered.joined(separator: "\n"), forType: .string)
        lastChangeCount = pb.changeCount   // our own write — don't re-capture it
    }

    /// Runs on-device OCR (Vision) over an image item and adds the recognized
    /// text back onto the shelf as a new text item.
    func extractText(from item: ShelfItem) {
        guard item.kind == .image,
              let url = fileURL(for: item),
              let image = NSImage(contentsOf: url),
              let cg = image.cgImage(forProposedRect: nil, context: nil, hints: nil) else { return }

        let request = VNRecognizeTextRequest { [weak self] req, _ in
            let lines = (req.results as? [VNRecognizedTextObservation])?
                .compactMap { $0.topCandidates(1).first?.string } ?? []
            let text = lines.joined(separator: "\n")
            guard !text.isEmpty else { return }
            DispatchQueue.main.async { self?.addText(text) }
        }
        request.recognitionLevel = .accurate
        request.usesLanguageCorrection = true

        let handler = VNImageRequestHandler(cgImage: cg, options: [:])
        DispatchQueue.global(qos: .userInitiated).async { try? handler.perform([request]) }
    }

    /// Puts an item's payload on the system clipboard.
    func copyToPasteboard(_ item: ShelfItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text, .link:
            pb.setString(item.text ?? item.name, forType: .string)
        case .image:
            if let url = fileURL(for: item), let img = NSImage(contentsOf: url) {
                pb.writeObjects([img])
            }
        case .file:
            if let url = fileURL(for: item) {
                pb.writeObjects([url as NSURL])
            }
        }
        lastChangeCount = pb.changeCount   // our own write — don't re-capture it
    }

    // MARK: - Internals

    private func insert(_ item: ShelfItem) {
        items.insert(item, at: 0)
        save()
    }

    private func load() {
        guard let data = try? Data(contentsOf: manifestURL),
              let decoded = try? JSONDecoder().decode([ShelfItem].self, from: data) else {
            return
        }
        // Drop any entries whose backing file vanished.
        items = decoded.filter { item in
            guard let name = item.fileName else { return true }
            return FileManager.default.fileExists(
                atPath: filesURL.appendingPathComponent(name).path)
        }
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(items) else { return }
        try? data.write(to: manifestURL, options: .atomic)
    }

    private func looksLikeURL(_ string: String) -> Bool {
        guard !string.contains(" "), !string.contains("\n") else { return false }
        guard let url = URL(string: string) else { return false }
        return url.scheme == "http" || url.scheme == "https"
    }

    private func prettyHost(_ string: String) -> String {
        URL(string: string)?.host ?? firstLine(string)
    }

    private func firstLine(_ string: String) -> String {
        let line = string.split(separator: "\n", maxSplits: 1).first.map(String.init) ?? string
        return line.count > 60 ? String(line.prefix(60)) + "…" : line
    }
}
